name: Build using Bazel

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [main]

jobs:
  bazel-build:
    name: Build using Bazel
    runs-on: ubuntu-24.04
  permissions:
    id-token: write
    contents: read
  steps:
    - uses: actions/checkout@v4.2.2
    - uses: ngalaiko/bazel-action@2.0.0
    - run: bazel build //src:main --enable_bzlmod --copt=-std=c++17
